# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-api
  namespace: financial-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: financial-api
  template:
    metadata:
      labels:
        app: financial-api
    spec:
      containers:
      - name: api
        image: financial-platform/api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: financial-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: financial-secrets
              key: redis-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: financial-secrets
              key: secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: financial-api-service
  namespace: financial-platform
spec:
  selector:
    app: financial-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-websocket
  namespace: financial-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: financial-websocket
  template:
    metadata:
      labels:
        app: financial-websocket
    spec:
      containers:
      - name: websocket
        image: financial-platform/websocket:latest
        ports:
        - containerPort: 8765
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: financial-secrets
              key: redis-url
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: financial-websocket-service
  namespace: financial-platform
spec:
  selector:
    app: financial-websocket
  ports:
  - protocol: TCP
    port: 8765
    targetPort: 8765
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: financial-api-hpa
  namespace: financial-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: financial-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
